### ISSUE TITLE
[Spectral profile sources] Python error when selecting raster source

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#275] opened 2022-11-25 10:59 UTC
How to reproduce:
* Open Spectral Library + Map View
* In the Spectral profile sources panel, expand the options and double click to select a raster source
* Error appears, see below

Also happens when data is loaded. So far it does not have bigger implications on the workflow.

![grafik](https://user-images.githubusercontent.com/15610561/203968033-2e47e5eb-6e90-4b50-a301-0e880c4cec7c.png)

```
An error has occurred while executing Python code: 

TypeError: arguments did not match any overloaded call:   QSize(): too many arguments   QSize(int, int): argument 1 has unexpected type 'float'   QSize(QSize): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/externals/htmlwidgets.py", line 73, in sizeFromContents
    size = widget.sizeHint()
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/externals/htmlwidgets.py", line 209, in sizeHint
    self.stored_size = QtCore.QSize(max_w, max_h)
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(int, int): argument 1 has unexpected type 'float'
  QSize(QSize): argument 1 has unexpected type 'float'


Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdad 

```

```
QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdad
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS




Active Python plugins
enmapboxplugin
3.11.0
send2google_earth
0.3.1
MetaSearch
0.3.6
sagaprovider
2.12.99
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
```

**Comment by jakimowb** [comment] 2022-12-01 16:46
@thielfab please test if this error is now gone

**Comment by thielfab** [comment] 2022-12-02 10:31
I built a version from the current main branch (Version 3.12alpha.5.20221201T174509.main Code d72bd228f9f ) but it is still present

**Comment by jakimowb** [comment] 2023-01-03 13:49
Indeed, looks like a Python 3.10 issue: https://bugs.python.org/issue37999. 
So far OSGeo4W QGIS uses Python 3.9. I'll test it with conda + Python 3.10

**Comment by jakimowb** [comment] 2023-01-03 22:34
@thielfab I am unable to reproduce with EnMAP-Box 3.11.1. on Python 3.11 + Qt 5.15.6

**Comment by thielfab** [comment] 2023-01-04 13:30
Maybe. Just tested with EnMAP-Box 3.11.1 and QGIS 3.28.2 in a fresh Ubuntu 22.04.1 docker install, and there it still exists.
```
Qt version 5.15.3
Python version 3.10.6
```

**Comment by jakimowb** [comment] 2023-03-29 21:25
>   File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/externals/htmlwidgets.py", line 209, in sizeHint
>     self.stored_size = QtCore.QSize(max_w, max_h)
> TypeError: arguments did not match any overloaded call:
>   QSize(): too many arguments
>   QSize(int, int): argument 1 has unexpected type 'float'
>   QSize(QSize): argument 1 has unexpected type 'float'

Fixed with https://github.com/EnMAP-Box/qgispluginsupport/commit/907a35b1e40d27735a7c385938449b4625d88bf4
and already pushed to main branch.

**Closed by jakimowb** 2023-03-29 21:25 UTC
Labels: bug
