### ISSUE TITLE
EnMAPBoxApplication error(s) in MacOS

### ISSUE THREAD

**Issue by saberioon** [EnMAP-Box/enmap-box#676] opened 2023-10-13 07:51 UTC
When I open the EnMAP-Box v 3.13.0 in my MacOS Sonoma 14.0 (Apple M1) , I get the missing Python packages, However, I have installed all packages using the pip as explained in the documentation. Then when I close it, I receive EnMAPBoxApplicaiton error(s) which have the below message. How can this be fixed ?

```
EnMAPBoxApplication error(s): 
ensomap: 
TypingError:Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function() found for signature:

>>> arange(Literal[int](0), int64)

There are 2 candidate implementations:
- Of which 1 did not match due to:
Overload in function 'np_arange': File: numba/np/arrayobj.py: Line 3842.
With argument(s): '(Literal[int](0), int64)':
Rejected as the implementation raised a specific error:
TypeError: '>' not supported between instances of 'Integer' and 'IntegerLiteral'
raised from /Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py:3837
- Of which 1 did not match due to:
Overload in function 'np_arange': File: numba/np/arrayobj.py: Line 3842.
With argument(s): '(int64, int64)':
Rejected as the implementation raised a specific error:
UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (IS_OP) found

File "Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py", line 3879:
def impl(start, stop=None, step=None, dtype=None):

# Allow for improved performance if given literal arguments.
lit_start = start_value if start_value is not None else start
^

raised from /Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/byteflow.py:269

During: resolving callee type: Function()
During: typing of call at /Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps/ensomap/hys/tools.py (77)


File "Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps/ensomap/hys/tools.py", line 77:
def get_crad(x, y):

qmax = -99999
for k in np.arange(0, nx):
^

Traceback:
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/gui/applications.py", line 368, in addApplicationFolder
apps = factory(self.mEnMAPBox)
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps/ensomap/__init__.py", line 35, in enmapboxApplicationFactory
from ensomap.enmapboxintegration import EnSoMAP
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
_module_ = __builtin_import__(name, *args, **kwargs)
File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps/ensomap/enmapboxintegration.py", line 32, in 
import hys
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
_module_ = __builtin_import__(name, *args, **kwargs)
File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps/ensomap/hys/__init__.py", line 26, in 
from .tools import *
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
_module_ = __builtin_import__(name, *args, **kwargs)
File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/mehdisaberioon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps/ensomap/hys/tools.py", line 68, in 
def get_crad(x, y):
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/decorators.py", line 198, in wrapper
disp.compile(sig)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
return func(*args, **kwargs)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/dispatcher.py", line 808, in compile
cres = self._compiler.compile(args, return_type)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/dispatcher.py", line 82, in compile
raise retval
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/dispatcher.py", line 92, in _compile_cached
retval = self._compile_core(args, return_type)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/dispatcher.py", line 105, in _compile_core
cres = compiler.compile_extra(self.targetdescr.typing_context,
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 603, in compile_extra
return pipeline.compile_extra(func)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 339, in compile_extra
return self._compile_bytecode()
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 401, in _compile_bytecode
return self._compile_core()
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 381, in _compile_core
raise e
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 372, in _compile_core
pm.run(self.state)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 341, in run
raise patched_exception
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 332, in run
self._runPass(idx, pass_inst, state)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
return func(*args, **kwargs)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 291, in _runPass
mutated |= check(pss.run_pass, internal_state)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 264, in check
mangled = func(compiler_state)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typed_passes.py", line 92, in run_pass
typemap, return_type, calltypes = type_inference_stage(
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typed_passes.py", line 70, in type_inference_stage
infer.propagate(raise_errors=raise_errors)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typeinfer.py", line 994, in propagate
raise errors[0]




```

**Comment by janzandr** [comment] 2023-10-13 09:51
There is currently a problem with the PIP Package Installer, which needs to be fixed: https://github.com/EnMAP-Box/enmap-box/issues/671

You can probably just ignore the error message and use the EnMAP-Box (except for the EnSoMap application).

Does that work?

**Comment by janzandr** [comment] 2023-10-13 09:52
Duplicate of #671.

**Closed by janzandr** 2023-10-13 09:52 UTC
