### ISSUE TITLE
[GEE Time Series Viewe] Composite Selection Mode doesn't work

### ISSUE THREAD

**Issue by breierlukas** [EnMAP-Box/enmap-box#340] opened 2023-01-24 12:23 UTC
Visualization in Image selection mode works. When trying Composite Selection Mode a Python error occurs.

`2023-01-24T13:19:45     WARNING    Traceback (most recent call last):
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 523, in onStretchAndUpdateLayerClicked
              self.calculateCumulativeCountCutStretch()
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 880, in calculateCumulativeCountCutStretch
              self.calculateCumulativeCountCutStretchForWms()
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 899, in calculateCumulativeCountCutStretchForWms
              eeCompositeProfile, eeCompositeRgb, visParams = self.eeComposite(limit)
              File "C:\Users/Lukas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
              retval = func(*args, **kwargs)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 1080, in eeComposite
              mapCanvasCrs = Utils.mapCanvasCrs()
              File "C:\Users/Lukas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 901, in wrapper
              memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
              File "C:\Users/Lukas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 110, in __init__
              self.arguments = signature.bind(*args, **kwargs).arguments
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\inspect.py", line 3062, in bind
              return self._bind(args, kwargs)
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\inspect.py", line 2977, in _bind
              raise TypeError(msg) from None
             TypeError: missing a required argument: 'mapCanvas'
             `

**Comment by janzandr** [comment] 2023-01-24 12:33
Duplicate of #244

**Closed by janzandr** 2023-01-24 12:33 UTC
