### ISSUE TITLE
short of spectral separability tests

### ISSUE THREAD

**Issue by dpoursanidis** [EnMAP-Box/enmap-box#494] opened 2023-05-31 16:56 UTC
Working with spectra, is important to be able to run spectral separability tests to explore the collected data. Any work on that for next releases? 

Mahalanobis, and other tests (https://opus.uleth.ca/server/api/core/bitstreams/8e76d869-e190-4d92-bbfc-1636518874f9/content and see pg 43 as example)?

**Comment by janzandr** [comment] 2023-06-01 07:21
Duplicate of #469.

**Comment by janzandr** [comment] 2023-08-15 14:37
Implemented in #469.

**Closed by janzandr** 2023-08-15 14:37 UTC
Labels: feature request, priority: high
