### ISSUE TITLE
Error when starting EnMAP

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#1047] opened 2024-12-07 04:16 UTC
I am using QGIS v. 3.40.1 and I get the following message after upgrading to the latest version of ENMAP 3.15.

2024-12-07T12:13:13     CRITICAL    Unable to load enmapboxprocessing.algorithm.algorithms
             expected string or bytes-like object, got 'NoneType'

Any thoughts?

**Comment by janzandr** [comment] 2024-12-07 14:33
Can't reproduce this under Windows. Have you restarted QGIS after installation?

**Comment by grantboxer** [comment] 2024-12-12 07:02
Hi Andreas,

I have had a similar problem with the Data Plotly plug-in and found if I do the following, it fixes the problem.
I have re-installed python3-pyarrow using the network installer and updated the file to version 15.02.01 and this seems to fix the problem. Maybe others can check this works for them as well?
Cheers Grant

**Comment by janzandr** [comment] 2024-12-12 08:25
Hi Grant, alright, so I would say that the problem had more to do with your QGIS/Python installation as such. Good that is works now. I think we can just close this.

**Closed** 2024-12-12 08:25 UTC
