### ISSUE TITLE
Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method on new QGIS 3.34.0 release

### ISSUE THREAD

**Issue by jgrn307** [EnMAP-Box/enmap-box#715] opened 2023-11-08 17:03 UTC
Hi all, I just upgraded to the release candidate of QGIS (3.34.0) and EnMAP Box is no longer loading properly (Python error log below).  Is there an easy fix for this?  Cheers!  I am using the latest Experimental version of the plugin on a Win64 box.  I also tried the non-experimental release and am getting the same errors.

```
2023-11-08T08:55:29     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~2.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\__init__.py", line 51, in classFactory
              plugin = EnMAPBoxPlugin(iface)
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 51, in __init__
              self.initialDependencyCheck()
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 77, in initialDependencyCheck
              from enmapbox.dependencycheck import missingPackageInfo, requiredPackages
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "C:\PROGRA~1/QGIS33~2.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 39, in 
              from enmapbox.qgispluginsupport.qps.utils import qgisAppQgisInterface
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "C:\PROGRA~1/QGIS33~2.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 3006, in 
              class SelectMapLayersDialog(QgsDialog):
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 3007, in SelectMapLayersDialog
              class LayerDescription(object):
              File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 3009, in LayerDescription
              def __init__(self, info: str, filters: QgsMapLayerProxyModel.Filters, allowEmptyLayer=False):
             AttributeError: type object 'QgsMapLayerProxyModel' has no attribute 'Filters'
             
```

**Comment by janzandr** [comment] 2023-11-09 09:29
Duplicate of #713. Is already fixed and will be released with v3.13.1 later todasy.

**Closed by janzandr** 2023-11-09 09:29 UTC
