### ISSUE TITLE
Drag&drop EnMAP-Box source to QGIS will open the source twice

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#60] opened 2022-09-16 14:59 UTC
In QGIS 3.26 and Box v3.11

![animation2](https://user-images.githubusercontent.com/45030715/190669062-2f3926c4-1910-48ee-8313-9ff4ffa79a1d.gif)

**Comment by jakimowb** [comment] 2022-09-23 10:07
related branch: https://github.com/EnMAP-Box/enmap-box/tree/issue_60

**Comment by jakimowb** [comment] 2022-09-28 18:30
@thielfab note that dragging a layer from the QGIS layer tree awai without ALT means to moving it to somewhere else. On thie QGIS side this is therefore the intended behaviour.

**Closed** 2022-10-04 17:40 UTC
Labels: bug
