### ISSUE TITLE
Installation on Windows: python packages installer error

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#683] opened 2023-10-16 09:27 UTC
Upon installing enmapbox Version 3.13.0 Code 7e553c8e8d4 on QGIS 3.32 (Windows 10 Version 2009), I get:
`Missing Python Package(s) Install missing
`
But the python packages installer does not start:

`Python error: An error has occurred while executing Python code: See message log (Python Error) for more details
`
Enmap Box log window:
```
2023-10-16T09:48:12     WARNING    The following 2 package(s) are not installed:
             
              typeguard (install by "C:\Program Files\QGIS 3.32.3\bin\qgis-bin.exe -m pip install --user typeguard==2.13.3")
              sympy (install by "C:\Program Files\QGIS 3.32.3\bin\qgis-bin.exe -m pip install --user sympy")
             
             Please follow the installation guide https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html#install-required-python-packages
             
             and install missing packages, e.g. with pip:
             
             
              $ python3 -m pip install -r C:\Users/Specim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\requirements.txt
```

Python log window:
```
2023-10-16T09:48:45     WARNING    Traceback (most recent call last):
              File "C:\Users/Specim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 811, in showPackageInstaller
              w.addPackages(requiredPackages())
              File "C:\Users/Specim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 1026, in addPackages
              self.loadPIPVersionInfo(packages)
              File "C:\Users/Specim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 957, in loadPIPVersionInfo
              self.startTask(task)
              File "C:\Users/Specim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 972, in startTask
              qgsTask.run()
              File "C:\Users/Specim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 275, in run
              process = subprocess.run(cmdList,
              File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\subprocess.py", line 528, in run
              raise CalledProcessError(retcode, process.args,
             subprocess.CalledProcessError: Command 'C:\Program Files\QGIS 3.32.3\bin\qgis-bin.exe -m pip list' returned non-zero exit status 1.
             
```

**Comment by janzandr** [comment] 2023-10-16 10:01
Yes, this is a known (critical) issue.
Duplicate of https://github.com/EnMAP-Box/enmap-box/issues/671

**Closed by janzandr** 2023-10-16 10:01 UTC
