### ISSUE TITLE
EnMAP-Box failing to load PRISMA data

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#455] opened 2023-04-20 05:18 UTC
Error message
Algorithm 'Import PRISMA L2D product' starting…
Input parameters:
{ 'badBandThreshold' : None, 'badPixelType' : [0], 'file' : 'J:\\Dropbox\\PRISMA\\Beasley_WA\\PRS_L2D_STD_20210726022639_20210726022644_0001\\PRS_L2D_STD_20210726022639_20210726022644_0001.he5', 'outputPrismaL2D_spectralCube' : 'TEMPORARY_OUTPUT', 'spectralRegion' : 0 }

Reading data with h5py API failed. Fall back to GDAL API, which is very slow on PRISMA BIP interleaved data: HDF5:"""J:\Dropbox\PRISMA\Beasley_WA\PRS_L2D_STD_20210726022639_20210726022644_0001\PRS_L2D_STD_20210726022639_20210726022644_0001.he5"""://HDFEOS/SWATHS/PRS_L2D_HCO/Data_Fields/VNIR_Cube
Reading data with h5py API failed. Fall back to GDAL API, which is very slow on PRISMA BIP interleaved data: HDF5:"""J:\Dropbox\PRISMA\Beasley_WA\PRS_L2D_STD_20210726022639_20210726022644_0001\PRS_L2D_STD_20210726022639_20210726022644_0001.he5"""://HDFEOS/SWATHS/PRS_L2D_HCO/Data_Fields/SWIR_Cube
Traceback (most recent call last):
File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 168, in processAlgorithm
self.writeSpectralCube(filenameSpectralCube, he5Filename, spectralRegion, badBandMultipliers, feedback)
File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 250, in writeSpectralCube
writer = driver.createFromArray(array, extent, crs)
File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapboxprocessing\driver.py", line 88, in createFromArray
raster.writeArray(array, overlap=overlap)
File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapboxprocessing\rasterwriter.py", line 23, in writeArray
bandList = range(1, self.bandCount() + 1)
File "C:\Users\Grant\AppData\Roaming\Python\Python39\site-packages\typeguard\_functions.py", line 264, in check_variable_assignment
check_type_internal(obj, expected_type, memo)
File "C:\Users\Grant\AppData\Roaming\Python\Python39\site-packages\typeguard\_checkers.py", line 667, in check_type_internal
checker(value, origin_type, args, memo)
File "C:\Users\Grant\AppData\Roaming\Python\Python39\site-packages\typeguard\_checkers.py", line 267, in check_list
raise TypeCheckError("is not a list")
typeguard.TypeCheckError: bandList is not a list

Execution failed after 116.76 seconds (1 minute 57 seconds)

I am using QGIS v3.30.1, and EnMAP-Box 3.12.0

**Comment by janzandr** [comment] 2023-04-22 11:23
Can't reproduce this.
Please check your **typeguard** version. It should be 2.13.3:
![image](https://user-images.githubusercontent.com/45030715/233781253-aa901fb2-7c8d-439c-b344-e95d102ce099.png)

If you have already installed typeguard 3.x, this is most likely the cause of the problem.
In that case, please downgrade to 2.13.3.

**Comment by janzandr** [comment] 2023-09-21 11:42
Missing user feedback, I'll close this for now. Please re-open if necessary.

**Closed by janzandr** 2023-09-21 11:42 UTC
Labels: bug, feedback

**Comment by janzandr** [comment] 2025-03-26 08:53
related to #430
