### ISSUE TITLE
trouble with numba>=0.57

### ISSUE THREAD

**Issue by HPWhiteCCRS** [EnMAP-Box/enmap-box#735] opened 2023-11-29 19:01 UTC
Hello. Attempting to get the EnMAP-Box on QGIS. Can you advise? When I use 
> python3 -m pip install -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/requirements.txt
I get errors and warnings, including: 
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /EnMAP-Box/enmap-box/main/requirements.txt (Caused by SSLError(SSLError(1, 'A failure in the SSL library occurred (_ssl.c:1129)')))

I then tried line by line. All seemed to work fine until
> python3 -m pip install numba>=0.57
Which gives me:
Access is denied.

I then tried 
>python3 -m pip install enpt-enmapboxapp
Which gives me: 
Defaulting to user installation because normal site-packages is not writeable
Collecting enpt-enmapboxapp
  Using cached enpt_enmapboxapp-0.7.8.tar.gz (471 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\pwhite\AppData\Local\Temp\pip-build-env-53e41est\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\pwhite\AppData\Local\Temp\pip-build-env-53e41est\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\pwhite\AppData\Local\Temp\pip-build-env-53e41est\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\pwhite\AppData\Local\Temp\pip-build-env-53e41est\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 42, in <module>
        File "<string>", line 25, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Thanks
H P White - HPWhite.CCRS@Gmail.com

**Comment by janzandr** [comment] 2023-11-30 08:01
> Hello. Attempting to get the EnMAP-Box on QGIS. Can you advise? When I use

Sorry, we are currently restructuring the installation guide. Please follow these instructions here:

https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation_new.html#qgis-installation-on-windows

**Comment by HPWhiteCCRS** [comment] 2023-12-05 14:38
Hi Andreas. when I try this usr_installation_new.html I get the following
error messages. Suggestions?

>pip install --upgrade --user -r
https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLError(1, 'A failure
in the SSL library occurred (_ssl.c:1129)'))':
/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLError(1, 'A failure
in the SSL library occurred (_ssl.c:1129)'))':
/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLError(1, 'A failure
in the SSL library occurred (_ssl.c:1129)'))':
/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLError(1, 'A failure
in the SSL library occurred (_ssl.c:1129)'))':
/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLError(1, 'A failure
in the SSL library occurred (_ssl.c:1129)'))':
/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt
ERROR: Could not install packages due to an OSError:
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max
retries exceeded with url:
/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt (Caused by
SSLError(SSLError(1, 'A failure in the SSL library occurred
(_ssl.c:1129)')))


*Peter*

______________________________________________

H. Peter White, Research Scientist / Chercheur scientifique
CCRS-CCMEO-NRCan   /   CCT-CCCOT-RNCan

Telephone/Téléphone : (343) 543-7301

Twitter: https://twitter.com/Rystic_Redbeard    LinkedIn:
https://www.linkedin.com/in/DrHPWhite/
<https://www.linkedin.com/in/drhpwhite/>   Skype: HPeterWhite

______________________________________________

**Comment by HPWhiteCCRS** [comment] 2023-12-05 20:57
In addition, when I run line-by-line, I get to
>python3 -m pip install enpt-enmapboxapp
before I get errors.


Collecting enpt-enmapboxapp
  Using cached enpt_enmapboxapp-0.7.8.tar.gz (471 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File
"C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py",
line 353, in <module>
          main()
        File
"C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py",
line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File
"C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py",
line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File
"C:\Users\admin-pwhite\AppData\Local\Temp\pip-build-env-29hbb_81\overlay\Lib\site-packages\setuptools\build_meta.py",
line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings,
requirements=['wheel'])
        File
"C:\Users\admin-pwhite\AppData\Local\Temp\pip-build-env-29hbb_81\overlay\Lib\site-packages\setuptools\build_meta.py",
line 295, in _get_build_requires
          self.run_setup()
        File
"C:\Users\admin-pwhite\AppData\Local\Temp\pip-build-env-29hbb_81\overlay\Lib\site-packages\setuptools\build_meta.py",
line 480, in run_setup
          super(_BuildMetaLegacyBackend,
self).run_setup(setup_script=setup_script)
        File
"C:\Users\admin-pwhite\AppData\Local\Temp\pip-build-env-29hbb_81\overlay\Lib\site-packages\setuptools\build_meta.py",
line 311, in run_setup
          exec(code, locals())
        File "<string>", line 42, in <module>
        File "<string>", line 25, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a
problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem
with pip.



*Peter*

______________________________________________

H. Peter White, Research Scientist / Chercheur scientifique
CCRS-CCMEO-NRCan   /   CCT-CCCOT-RNCan

Telephone/Téléphone : (343) 543-7301

Twitter: https://twitter.com/Rystic_Redbeard    LinkedIn:
https://www.linkedin.com/in/DrHPWhite/
<https://www.linkedin.com/in/drhpwhite/>   Skype: HPeterWhite

______________________________________________

**Comment by janzandr** [comment] 2023-12-06 08:08
I can reproduce the problem with **enpt_enmapboxapp-0.7.8** (maintained by @danschef)
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/7fa50cdf-ae8b-49bd-a190-c7cb0be075f7)

@danschef can you please have a look at the EnPT PIP package.

**Comment by danschef** [comment] 2023-12-06 10:05
Fix is in progress.

**Comment by danschef** [comment] 2023-12-06 11:03
enpt_enmapboxapp v0.7.9 is now released on PyPI and will soon be available from conda-forge. It fixes the ModuleNotFoundError during the installation.

**Comment by janzandr** [comment] 2023-12-06 13:56
Thanks @danschef, I can confirm that the PIP install is working again.

**Comment by janzandr** [comment] 2023-12-06 13:58
> @HPWhiteCCRS, regarding the _**"ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host=..."**_ error see:

https://stackoverflow.com/questions/71788177/pip-install-package-error-could-not-install-packages-due-to-an-oserror

**Closed by janzandr** 2023-12-06 13:58 UTC

**Comment by HPWhiteCCRS** [comment] 2023-12-06 19:53
Thank you. I can confirm that I have successful now run

>python3 -m pip install enpt-enmapboxapp


As a note, I am still unable to run

  >python3 -m pip install -r
https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/requirements.txt

as suggested on
https://enmap-box.readthedocs.io/en/latest/general/faq_trouble.html

Nor could I successfully run

pip install --upgrade --user -r
https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt

as suggested on
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation_new.html#qgis-installation-on-windows

Appreciate the help.


*Peter*

______________________________________________

H. Peter White, Research Scientist / Chercheur scientifique
CCRS-CCMEO-NRCan   /   CCT-CCCOT-RNCan

Telephone/Téléphone : (343) 543-7301

Twitter: https://twitter.com/Rystic_Redbeard    LinkedIn:
https://www.linkedin.com/in/DrHPWhite/
<https://www.linkedin.com/in/drhpwhite/>   Skype: HPeterWhite

______________________________________________

**Comment by janzandr** [comment] 2023-12-07 09:06
> Thank you. I can confirm that I have successful now run
> python3 -m pip install enpt-enmapboxapp

Good.

> As a note, I am still unable to run python3 -m pip install -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/requirements.txt as suggested on https://enmap-box.readthedocs.io/en/latest/general/faq_trouble.html 

This requirements.txt is not available anymore... docs are outdated.

> Nor could I successfully run pip install --upgrade --user -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt as suggested on https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation_new.html#qgis-installation-on-windows Appreciate the help. *Peter*

This requierements.txt file should work.
You mentioned the error **_"ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host=..."_**.
This is most likely a problem with your computer and/or internet connection.
Please read here for more details on how to solve this:
https://stackoverflow.com/questions/71788177/pip-install-package-error-could-not-install-packages-due-to-an-oserror

**Comment by HPWhiteCCRS** [comment] 2024-03-12 16:30
Hi - I have a new computer and will be putting the EnMAP toolbox on it. I
noticed the old instructions on your web page are not updated. Are there
any new instructions about getting the EnMAP toolbox once I get QGIS
installed?

Thanks


*Peter*

______________________________________________

H. Peter White, Research Scientist / Chercheur scientifique
CCRS-CCMEO-NRCan   /   CCT-CCCOT-RNCan

Telephone/Téléphone : (343) 543-7301

Twitter: https://twitter.com/Rystic_Redbeard    LinkedIn:
https://www.linkedin.com/in/DrHPWhite/
<https://www.linkedin.com/in/drhpwhite/>   Skype: HPeterWhite

______________________________________________

**Comment by janzandr** [comment] 2024-03-14 08:40
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html#installation
