### ISSUE TITLE
Sentinel-3 data is not visualized correct

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#817] opened 2024-02-23 12:50 UTC
Sentinel-3 datasets are display wrong:

EnMAP-Box (upper right shows the Bosporous):
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/efd756a3-3e57-440b-becd-900bae904257)

SNAP (lower right shows Bosporous):
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/bc9929db-fec6-4dcf-a636-1212bac31357)

Test data can be downloaded from https://browser.dataspace.copernicus.eu

**Comment by janzandr** [comment] 2024-02-23 13:13
A Sentinel 3 import algo could take care of it. Currently, we don't have one.
https://github.com/EnMAP-Box/enmap-box/issues/126

**Comment by janzandr** [comment] 2024-02-27 10:01
Duplicate of #126

**Closed by janzandr** 2024-02-27 10:01 UTC
